### ISSUE TITLE
openni_launchとNITE-1.5のSampleを同時に立ちあげるとdepthが左右反転する

### ISSUE THREAD

**Issue by ishiguroJSK** [jsk-ros-pkg/jsk_openni_kinect#15]
という今のとこどうでもいい不具合報告です
(ちなみにNiViewerだとRGB-Depthもろとも反転する)
![a](https://cloud.githubusercontent.com/assets/18138979/15640599/a0f4c43c-2674-11e6-85da-fb22e22f2cd9.png)
![b](https://cloud.githubusercontent.com/assets/18138979/15640600/a0f53c14-2674-11e6-8a31-90e2547e6a76.png)

**Comment by k-okada** [comment]
https://github.com/ros-drivers/openni_tracker/blob/hydro-devel/openni_tracker.xml#L17
をtrueにすると治るきがします．ためしてみてください．ただし，trackerダケを起ち上げると反転するきがします．
もし−ソースの中で同じようにmirrorしている部分があれば，オプションで切り替えられるようにすれば
いいですね．
OpenNI2の方も試してみて下さい．そっちはこの問題はないきがします．

--
◉ Kei Okada


On Mon, May 30, 2016 at 2:51 PM, Yasuhiro Ishiguro <notifications@github.com

**Comment by ishiguroJSK** [comment]
オプションがあるとのことでしたら色々調整できそうです．
困った時のために覚えておきます．
ありがとうございます．
